config/routes.rb
Rails.application.routes.draw do

  # User↓========================================================================================
    root            to: "user/top#index"
    get "/shop",    to: "user/top#shop"
    get "/store/:id", to: "user/top#details", as: :details
  # devise↓ =====================================================================================
    devise_for :admins, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    devise_for :masseurs
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    devise_scope :user do
      get "/user/:id", :to => "users/registrations#show", as: :user
    end

    devise_for :users, controllers: {
      sessions:      'users/sessions',
      passwords:     'users/passwords',
      registrations: 'users/registrations',
      omniauth_callbacks: "users/omniauth_callbacks"
    }
    devise_for :store_managers, :controllers => {
      :registrations => 'store_managers/registrations',
      :sessions => 'store_managers/sessions'
    }
    devise_scope :store_manager do
      get "store_managers/:id", :to => "store_managers/registrations#show", as: "store_managers_show"
      get "store_managers/:id/reservations", :to => "store_managers/registrations#index", as: "store_managers_index"
      get "store_manager/:id/detales", :to => "store_managers/registrations#detales", as: "store_managers_detales"
      get "store_managers/sign_out", :to => "store_managers/sessions#destroy"
    end

    # devise_scope :store_managers do
    #   get "sign_in", :to => "store_managers/sessions#new"
    #   get "sign_out", :to => "store_managers/sessions#destroy"
    # end


    

  # Admin↓========================================================================================
    namespace :admin do
    #  get '/top', to: 'admins#top'
    end

  # Masseur↓========================================================================================
    namespace :masseur do

    end

  # Store_manager↓========================================================================================
    namespace :store_manager do
      get "/:id/top", to: 'top_page#top'
      patch "update_calendar_status", to: 'top_page#update_calendar_status'
      resources :store
      resources :plans
      resources :masseurs, except: :show
      # 出張範囲のrouting↓========================================================================================
      get "/masseurs/business_trip_ranges", :to => "/store_manager/business_trip_ranges#index"
      get "/masseurs/:masseur_id/business_trip_ranges/edit", :to => "/store_manager/business_trip_ranges#edit", as: "business_trip_ranges_edit"
      get "/masseurs/:masseur_id/business_trip_ranges/show", :to => "/store_manager/business_trip_ranges#show", as: "business_trip_ranges_show"
      patch "/masseurs/:masseur_id/business_trip_ranges/update", :to => "/store_manager/business_trip_ranges#update", as: "business_trip_ranges_update"
      get "/masseurs/:masseur_id/business_trip_ranges/cities_select", :to => "/store_manager/business_trip_ranges#cities_select", as: "cities_select_business_trip_ranges"
    end

    # SmartYoyaku webhook↓==========================================================================
    namespace :smart_yoyaku do
      post "webhook", to: 'webhook#update_order_plan'
    end
    
end

app/controllers/store_manager/base.rb
class StoreManager::Base < ApplicationController
  before_action :sign_in_store_manager, only:[:top]
  before_action :correct_store_manager, only:[:top]
  layout 'store_manager'

  private
  # アクセスしたマッサージ師が現在ログインしているユーザーか確認します。
  def correct_store_manager
    unless StoreManager.find_by(id: params[:id]) == current_store_manager
      flash[:danger] = "アクセス権限がありません。"
      redirect_to store_manager_url(current_store_manager)
    end
  end
  # ログインしているかどうかの判定
  def sign_in_store_manager
    unless store_manager_signed_in?
      flash[:danger] = "ログインしてください。"
      redirect_to store_manager_session_url
    end
  end
end

app/controllers/store_manager/business_trip_ranges_controller.rb
class StoreManager::BusinessTripRangesController < StoreManager::Base
  
  include StoreManager::BusinessTripRangesHelper
  
  before_action :set_masseur, only: [:edit, :update, :show]
  before_action :corrrect_store_manager, only: [:edit, :update, :show]
  
  def index
    @store = current_store_manager.store
    @masseurs = @store.masseurs
  end
  
  
  
  def edit
    @prefectures = Prefecture.all
    @ranges = @current_masseur.business_trip_ranges
  end
  
  def update
    # チェックがあった場合
    if params[:masseur].present?
      @current_masseur.update(city_business_trip_range_params)
      flash[:success] = "出張範囲を更新しました。"
      redirect_to store_manager_masseurs_business_trip_ranges_url
    # 一つもチェックがなかった場合
    else
      flash[:danger] = "出張範囲を選択してください。"
      render :edit
    end
  end
  
  def show
    @business_trip_ranges = @current_masseur.business_trip_ranges
    # 閲覧中のマッサージ師が持っている出張範囲(市町村)が属している都道府県IDを配列にして取得
    @prefecture_ids = @current_masseur.business_trip_ranges.pluck(:city_id).map {|id| City.find_by(id: id).prefecture_id } 
    # 閲覧中のマッサージ師が持っているcity_idを配列で取得
    @city_ids = @current_masseur.business_trip_ranges.pluck(:city_id)
  end
  
  def city_select
    init(params[:prefecture_id].to_i)
  end
  
  private
  
  def set_masseur
    @current_masseur = Masseur.find(params[:masseur_id])
  end
  
  def city_business_trip_range_params
    if params[:masseur].present?
      params.require(:masseur).permit(city_ids: [])
    end
  end
  
  def corrrect_store_manager
    unless current_store_manager.store.masseurs.ids.include?params[:masseur_id].to_i
      flash[:danger] = "アクセス権限がありません。"
      redirect_to store_manager_url(current_store_manager)
    end
  end

end

app/controllers/store_manager/masseurs_controller.rb
class StoreManager::MasseursController < StoreManager::Base
  include SmartYoyakuApi::Staff

  before_action :authenticate_store_manager!
  before_action :corrrect_store_manager, only: [:edit, :update, :destroy]
  before_action :set_masseur, only: [:edit, :update, :destroy] 

  #def new
  #  @massuer = Masseur.new
  #end

  #def create
  #  @masseur = Masseur.new(masseur_create_params)
  #  if @masseur.save
  #    flash[:success] = "新規マッサージ師を登録しました。"
  #    redirect_to store_manager_masseurs_url
  #  else
  #    flash[:danger] = "入力内容に誤りがあったため登録できませんでした。"
  #    render :new
  #  end
  #end

  def index
    @store = current_store_manager.store
    @masseurs = @store.masseurs
  end

  def edit
  end

  def update
    ActiveRecord::Base.transaction do
      if @masseur.update(masseur_update_params)
        flash[:success] = "#{@masseur.masseur_name}の情報を更新しました。"
        redirect_to store_manager_masseurs_url
        # 予約システムのStaff情報を更新
        @response = update_staff(@masseur)
        unless JSON.parse(@response)["status"] == "200"
          # 例外を発生させる
          raise StandardError, "予約システムでstaffのupdateに失敗しました。"
        end
      else
        flash.now[:danger] = "入力内容に誤りがあったため更新できませんでした。"
        render :edit
      end
    end
  end

  #def destroy
  #  if @masseur.destroy
  #   flash[:success] = "#{@masseur.masseur_name}を削除しました。"
  #    redirect_to store_manager_masseurs_url
  #  else
  #    flash[:danger] = "#{@masseur.masseur_name}を削除することができませんでした。"
  #    redirect_to store_manager_masseurs_url
  #  end
  #end

  private

    # masseurをcreateする際のストロングパラメーター
    #def masseur_create_params
    #  if params[:masseur]
    #    params.require(:masseur).permit(:masseur_name, :email, :adress, :phone_number, :password,
    #                                    :password_confirmation).merge(store_id: current_store_manager.store.id)
    #  else
    #    params.permit(:masseur_name, :email, :adress, :phone_number, :password,
    #                  :password_confirmation).merge(store_id: current_store_manager.store.id)
    #  end
    #end

    # masseurをupdateする際のストロングパラメーター
    def masseur_update_params
      if params[:masseur][:password].blank? && params[:masseur][:password_confirmation].blank?
        params[:masseur].delete(:password)
        params[:masseur].delete(:password_confirmation)
      end
      params.require(:masseur).permit(:masseur_name, :email, :adress, :phone_number, :password, :password_confirmation, category_ids: [])
    end

    def set_masseur
      @masseur = Masseur.find(params[:id])
    end

    # current_store_managerと紐づいていないmasseurの操作は不可
    def corrrect_store_manager
      unless current_store_manager.store.masseurs.ids.include?params[:id].to_i
        flash[:danger] = "アクセス権限がありません。"
        redirect_to store_manager_url(current_store_manager)
      end
    end
end

app/controllers/store_manager/plans_controller.rb
class StoreManager::PlansController < StoreManager::Base
  include SmartYoyakuApi::TaskCourse
  before_action :sign_in_store_manager
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :corrrect_store_manager, only: [:edit, :update, :destroy]

  def index
    @plans = current_store_manager.store.plans
  end

  def new
    @plan = Plan.new
    @plan_image = @plan.plan_images.build
  end

  def create
    @plan = current_store_manager.store.plans.build(plan_params)
    ActiveRecord::Base.transaction do
      if @plan.save
        response = task_course_create(@plan)
        response_parse = JSON.parse(response)
        @plan.update!(course_id: response_parse['data']['id'])
        flash[:success] = '新規作成に成功しました。'
        redirect_to store_manager_plans_url
      else
        flash.now[:danger] = '入力情報に誤りがありました。もう一度入力情報を確認して下さい。'
        render :new
      end
    end
  end

  def show
    @plan_images = PlanImage.find_by(plan_id: @plan)
    unless @plan_images.nil?
      @count_plan_image = @plan_images.plan_image.count
    end
  end

  def edit
  end

  def update
    ActiveRecord::Base.transaction do
      if @plan.update(plan_params)
        response = task_course_update(@plan)
        if JSON.parse(response)['status'] == "200"
          flash[:success] = "#{@plan.plan_name}の情報を更新しました。"
          redirect_to store_manager_plans_url
        else
          raise RuntimeError
        end
      else
        flash.now[:danger] = "入力内容に誤りがあったため更新できませんでした。"
        render :edit
      end
    end
  end

  def destroy
    ActiveRecord::Base.transaction do
      if @plan.destroy
        response = task_course_delete(@plan)
        if JSON.parse(response)['status'] == "200"
          flash[:success] = "#{@plan.plan_name}を削除しました。"
        else
          raise RuntimeError
        end
      else
        flash[:danger] = '削除に失敗しました。再度やり直してください。'
      end
    redirect_to store_manager_plans_url(current_store_manager)
    end
  end

  private

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def plan_params
    params.require(:plan).permit(:store_id, :plan_name, :plan_content, :plan_time, :plan_price, plan_images_attributes:[:id, {plan_image: []},:remove_plan_image ])
  end

  def sign_in_store_manager
    unless store_manager_signed_in?
      flash[:danger] = "アカウント登録もしくはログインしてください。"
      redirect_to store_manager_session_url
    end
  end

  def corrrect_store_manager
    unless current_store_manager.store.plans.ids.include?params[:id].to_i
      flash[:danger] = "アクセス権限がありません。"
      redirect_to store_manager_url(current_store_manager)
    end
  end
end

app/controllers/store_manager/store_controller.rb
class StoreManager::StoreController < StoreManager::Base
  include SmartYoyakuApi::Calendar
  
  before_action :sign_in_store_manager, only: [:edit]
  before_action :correct_store, only: [:edit]

  def new
  end

  def create
  end

  def edit
    @store = current_store_manager.store
  end

  def update
    @store = current_store_manager.store
    ActiveRecord::Base.transaction do
      if @store.update(store_params)
        flash[:success] = "#{@store.store_name}の情報を更新しました。"
        redirect_to store_manager_url(current_store_manager)
        # 予約システム側のCalendar情報を更新
        @response = update_calendar(@store)
        unless JSON.parse(@response)["status"] == "200"
          raise StandardError, "予約システムでcalendarのupdateに失敗しました。"
        end
      else
        flash.now[:danger] = "入力内容に誤りがあったため更新できませんでした。"
        render :edit
      end
    end
  end

  private
    
    # ログインしているかどうかの判定
    def sign_in_store_manager
      unless store_manager_signed_in?
        flash[:danger] = "アカウント登録もしくはログインしてください。"
        redirect_to store_manager_session_url
      end
    end
    # urlに含まれるstore.idがcurrent_store_managerと紐づいていない場合警告
    def correct_store
      unless params[:id] == current_store_manager.store.id.to_s
        flash[:danger] = "アクセス権限がありません。"
        redirect_to store_manager_url(current_store_manager)
      end
    end

    def store_params
      params.require(:store).permit(:store_name, :adress, :store_phonenumber, :store_description, store_images_attributes:[:id, {store_image: []},:remove_store_image ])
    end
end

app/controllers/store_manager/store_manager_controller.rb
class StoreManager::StoreManagerController < StoreManager::Base

  def new
  end

end

app/controllers/store_manager/top_page_controller.rb
class StoreManager::TopPageController < StoreManager::Base
  include SmartYoyakuApi::Calendar
  before_action :set_store_manager_and_store

  def top   
    if @store_manager.order_plan.nil?
      flash.now[:notice] = "現在ご利用中のプランは【無料プラン】となっており、#{@store.store_name}様のページは非公開となっております。<br>
                            「登録内容の編集」から有料プランをご契約いただきますとページが公開され、お客様からのご予約が可能となります。".html_safe
    end
  end

  def update_calendar_status
    set_status
    # 予約カレンダーの表示を切り替える
    @response = update_holiday_flag(@store, @status)
    @store.update!(calendar_status: JSON.parse(@response)["calendar_status"])
    flash.now[:notice] = "#{flash_message}"
    render :top
  end

  private

    def set_store_manager_and_store
      @store_manager = current_store_manager
      @store = @store_manager.store
    end

    # 現在公開中の場合「private(非公開)」、非公開中の場合「released(公開中)」をset
    def set_status
      @status =
        @store.calendar_status == "released" ? "private" : "released"
    end

    # 更新後のcalendar_statusに合わせてメッセージを変更
    def flash_message
      @store.calendar_status == "released" ? "カレンダーを公開しました。" : "カレンダーを非公開にしました。"
    end
end

app/controllers/store_managers/confirmations_controller.rb
# frozen_string_literal: true

class StoreManagers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/store_managers/unlocks_controller.rb
# frozen_string_literal: true

class StoreManagers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/store_manager/business_trip_ranges_helper.rb
module StoreManager::BusinessTripRangesHelper
  require 'net/http'
  require 'uri'
  require 'json'
  
  # 都道府県のAPIを叩き、データを出力
  def prefectures_api(url)
    uri = URI.parse(URI.escape(url))

    https = Net::HTTP.new(uri.host, uri.port)
    https.use_ssl = true

    param = {}
    param['X-API-KEY'] = ENV['RESAS_API'] # 自分が取得したAPI-KEY

    req = Net::HTTP::Get.new(uri.request_uri, param)
    res = https.request(req)

    json = res.body
    result = JSON.parse(json)
  end
  
  # def set_prefectures
  #   # 現在のマッサージ師に紐づく出張範囲が登録されていなかった場合、都道府県のデータを作成
  #   if @current_masseur.business_trip_ranges.blank?
  #     ActiveRecord::Base.transaction do
  #       # Prefecture.all.each { |prefecture| @current_masseur.business_trip_ranges.create!(prefecture_id: prefecture.id, prefecture_name: prefecture.name) }
  #       # 東京に紐づげられた市/区のデータを作成
  #       City.all.each { |city| @current_masseur.business_trip_ranges.create!(city_name: city.name, city_id: city.id) }
  #     end
  #   end

  # rescue ActiveRecord::RecordInvalid
  #   flash[:danger] = "ページ情報の取得に失敗しました、再アクセスしてください。"
  #   redirect_to new_store_manager_masseur_business_trip_range_url
  # end
  
end

app/helpers/store_manager/plans_helper.rb
module StoreManager::PlansHelper

  # @plans.firstの削除ボタンのみ非表示
  def delete_plan_btn(plan, plans)
    unless plan == plans.first
      link_to "削除", store_manager_plan_path(plan), method: :delete,
      data: { confirm: "#{plan.plan_name} を削除しますか？" } , class:"btn btn-outline-danger"
    end
  end
end

app/helpers/store_manager/store_helper.rb
module StoreManager::StoreHelper
end

app/helpers/store_manager/store_manager_helper.rb
module StoreManager::StoreManagerHelper
end

app/helpers/store_manager/top_page_helper.rb
module StoreManager::TopPageHelper

  # カレンダーの表示／非表示切り替えボタン
  def calendar_btn
    if current_store_manager.order_plan.present?
      link_to "予約カレンダーを#{calendar_btn_message}する", store_manager_update_calendar_status_path, method: :patch,
      data: { confirm: "予約カレンダーを#{calendar_btn_message}します。" } , class: "btn btn-outline-secondary"
    end
  end

  # 切り替えボタンのメッセージ
  def calendar_btn_message
    current_store_manager.store.calendar_status == "released" ? "非公開に" : "公開"
  end
end

app/views/store_manager/plans/edit.html.erb
<h2 class="title">施術プラン/料金設定<p style="font-size: 13px;">サイトに記載する施術メニュー、料金の設定を行ってください。</p></h2>
<div class="col-md-8 offset-2">
  <% flash.each do |message_type, msg| %>
    <div class="mt-4 alert alert-<%= message_type %>"><%= msg %></div>
  <% end %>
  <%= form_with(model: @plan, url: store_manager_plan_path, method: :PATCH, local: true) do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="form-2">
      <div class="flex-parent-new-page2">
        <!--<div class="left-side">
          プラン写真<span class="entrust-label">任意</span><br>
          <img src="" height="220" width="220"><br>
          <button class="file-button" disabled>ファイルを選択</button>
        </div>-->
        <div class="">
          <div class="field mt-3">
            <%= f.label "プラン名", class: "" %><span class="necessary-label">必須</span><br>
            <%= f.text_field :plan_name, class: "form-control", required: true %>
          </div>
          <div class="field mt-3">
            <%= f.label "プラン内容", class: "" %><span class="necessary-label">必須</span><br>
            <%= f.text_area :plan_content, class: "form-control", required: true %>
          </div>
          <div class="field mt-3">
            <%= f.label "プラン時間(単位/分)", class: "" %><span class="necessary-label">必須</span><br>
            <%= f.number_field :plan_time, class: "form-control", required: true %>
          </div>
          <div class="field mt-3">
            <%= f.label "プラン料金(税込)", class: "" %><span class="necessary-label">必須</span><br>
            <%= f.number_field :plan_price, class: "form-control", required: true %>
          </div>
          <div class="field mt-3">
            <% unless @plan.plan_images.any? %>
              <%= f.fields_for :plan_images, @plan.plan_images.build do |pf| %>
                <%= pf.label :plan_image %><br>
                <%= pf.file_field :plan_image, multiple: true %>
              <% end %>
            <% else %>
              <%= f.fields_for :plan_images do |pf| %>
                <%= pf.label :plan_image %><br>
                <%= pf.file_field :plan_image, multiple: true %><br>
                <span class="image_notice">※画像の更新をする場合は添付する画像を選択してください。</span>
                <div class="field mt-3">
                  <span><%= pf.check_box :remove_plan_image %> &ensp;画像の削除</span>
                  <p class="image_notice">※画像を削除する場合はチェックボックスにチェックを入れてください。</p>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="create-button-center">
        <%= f.submit "更新", class: "create-button" %>
      </div>
    </div>
  <% end %>
  <div class="return-btn"><%= link_to "登録内容の一覧に戻る", store_manager_plans_path %></div>
</div>

app/views/store_manager/plans/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-2">
      <% flash.each do |message_type, msg| %>
        <div class="mt-4 alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
        <h3 class="showpage-title text-center"><%= current_store_manager.store.store_name %>の登録プラン一覧</h3>
        <div class="new-btn-show">
          <span class="btn btn-outline-primary"><%= link_to "新規登録", new_store_manager_plan_path %></span>
        </div>
         <% @plans.each do |plan| %>
           <table class="table">
              <tbody>
                <tr>
                  <td class="align-middle"><%= link_to plan.plan_name.truncate(15), store_manager_plan_path(plan)  %></td>
                  <td class="text-right">
                    <%= link_to "編集", edit_store_manager_plan_path(plan), class:"btn btn-outline-primary" %>
                    <%= delete_plan_btn(plan, @plans) %>
                  </td>
                </tr>
              </tbody>
           </table>
         <% end %>
       <br><br><%= link_to "登録内容の編集に戻る", store_managers_show_path(current_store_manager) %><br><br><br>
    </div>
  </div>
</div>

app/views/store_manager/plans/new.html.erb
<h2 class="title">施術メニュー/料金設定<p style="font-size: 13px;">サイトに記載する施術メニュー、料金の設定を行ってください。</p></h2>

<div class="col-md-8 offset-2">
  <% flash.each do |message_type, msg| %>
    <div class="mt-4 alert alert-<%= message_type %>"><%= msg %></div>
  <% end %>
    <%= form_with(model: @plan, url: store_manager_plans_path, method: :post, local: true) do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="form-2">
      <div class="flex-parent-new-page2">
        <div class="right">
          <%= f.label "プラン名", class: "" %><span class="necessary-label">必須</span><br>
          <%= f.text_field :plan_name, class: "form-control", required: true %>

          <%= f.label "プラン内容", class: "" %><span class="necessary-label">必須</span><br>
          <%= f.text_area :plan_content, class: "form-control", required: true %>

          <%= f.label "プラン時間(単位/分)", class: "" %><span class="necessary-label">必須</span><br>
          <%= f.number_field :plan_time, class: "form-control", required: true %>

          <%= f.label "プラン料金(税込)", class: "" %><span class="necessary-label">必須</span><br>
          <%= f.number_field :plan_price, class: "form-control", required: true %>
        <!--<div class="left-side">-->
          <%= f.fields_for :plan_images do |pif| %>
            <%= pif.label :plan_image, class:"mr-2" %><br>
            <%= pif.file_field :plan_image, multiple: true %>
          <% end %>
        <!--</div>-->
        </div>
      </div>
      <div class="create-button-center">
        <%= f.submit "新規作成", class: "create-button" %>
      </div>
    <% end %>
    </div>
  <div class="return-btn"><%= link_to "登録内容の一覧に戻る", store_manager_plans_path %></div>
</div>

app/views/store_manager/plans/show.html.erb
<div class="col-md-8 offset-2">
  <h3 class="my-5 text-center">プラン詳細</h3>
    <div class="outer-frame">
      <div class="flex-parent-show-page">
        <div class="left-image cover">
          <% unless @plan_images.nil? %>
            <% unless @count_plan_image == 0 %>
              <div id="cover" class="m-width_80">
                <div class="main-frame">
                  <img id="main-img" class="width_image" src="<%= @plan_images.plan_image[0].url %>">
                </div>
                <% @count_plan_image.times do |n| %>
                  <img class="thumbnails smole_image p_top " src="<%= @plan_images.plan_image[n].url %>" data-imagesrc="<%= @plan_images.plan_image[n].url %>" >
                <% end %>
              </div>
            <% else %>
              <img src="/images/no_image.jpg" alt="" class="image_solid width_image">
            <% end %>
          <% else %>
            <img src="/images/no_image.jpg" alt="" class="image_solid width_image">
          <% end %>
        </div>
        <div class="right-side right_width">
          <div class="title-frame">
            <div class="plan-title">
              <strong><%= @plan.plan_name %></strong>
            </div>
          </div>
          <div class="content-frame">
            <div class="plan-content">
              <%= simple_format(@plan.plan_content) %>
            </div>
          </div>
          <div class="price-frame">
            <div class="price-time">
              <span class="time-required">所要時間　<%= @plan.plan_time %>分</span><span class="time_price">　<%= @plan.plan_price %>円(税込)</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  <div class="return-btn-show"><%= link_to "登録内容の一覧に戻る", store_manager_plans_path %></div>
</div>

<script>
  var thumbs =document.querySelectorAll('.thumbnails');
  for (var i =0 ; i < thumbs.length; i++ ) {
  thumbs[i].onclick = function() {
  document.getElementById('main-img').src = this.dataset.imagesrc;
  };
}
</script>