config/routes.rb
Rails.application.routes.draw do

  # User↓========================================================================================
    root            to: "user/top#index"
    get "/shop",    to: "user/top#shop"
    get "/store/:id", to: "user/top#details", as: :details
  # devise↓ =====================================================================================
    devise_for :admins, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    devise_for :masseurs
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    devise_scope :user do
      get "/user/:id", :to => "users/registrations#show", as: :user
    end

    devise_for :users, controllers: {
      sessions:      'users/sessions',
      passwords:     'users/passwords',
      registrations: 'users/registrations',
      omniauth_callbacks: "users/omniauth_callbacks"
    }
    devise_for :store_managers, :controllers => {
      :registrations => 'store_managers/registrations',
      :sessions => 'store_managers/sessions'
    }
    devise_scope :store_manager do
      get "store_managers/:id", :to => "store_managers/registrations#show", as: "store_managers_show"
      get "store_managers/:id/reservations", :to => "store_managers/registrations#index", as: "store_managers_index"
      get "store_manager/:id/detales", :to => "store_managers/registrations#detales", as: "store_managers_detales"
      get "store_managers/sign_out", :to => "store_managers/sessions#destroy"
    end

    # devise_scope :store_managers do
    #   get "sign_in", :to => "store_managers/sessions#new"
    #   get "sign_out", :to => "store_managers/sessions#destroy"
    # end


    

  # Admin↓========================================================================================
    namespace :admin do
    #  get '/top', to: 'admins#top'
    end

  # Masseur↓========================================================================================
    namespace :masseur do

    end

  # Store_manager↓========================================================================================
    namespace :store_manager do
      get "/:id/top", to: 'top_page#top'
      patch "update_calendar_status", to: 'top_page#update_calendar_status'
      resources :store
      resources :plans
      resources :masseurs, except: :show
      # 出張範囲のrouting↓========================================================================================
      get "/masseurs/business_trip_ranges", :to => "/store_manager/business_trip_ranges#index"
      get "/masseurs/:masseur_id/business_trip_ranges/edit", :to => "/store_manager/business_trip_ranges#edit", as: "business_trip_ranges_edit"
      get "/masseurs/:masseur_id/business_trip_ranges/show", :to => "/store_manager/business_trip_ranges#show", as: "business_trip_ranges_show"
      patch "/masseurs/:masseur_id/business_trip_ranges/update", :to => "/store_manager/business_trip_ranges#update", as: "business_trip_ranges_update"
      get "/masseurs/:masseur_id/business_trip_ranges/cities_select", :to => "/store_manager/business_trip_ranges#cities_select", as: "cities_select_business_trip_ranges"
    end

    # SmartYoyaku webhook↓==========================================================================
    namespace :smart_yoyaku do
      post "webhook", to: 'webhook#update_order_plan'
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :reviews
  has_many :social_profiles, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :omniauthable, omniauth_providers: %i[line google]

  enum gender: { "male": 0, "female": 1, "other": 2 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: { in: 1..30 }       
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :password, presence: true, length: { minimum: 6 } ,allow_nil: true
  validates :address, presence: true, length: { in: 5..60 }
  validates :gender, presence: true
  validates :nickname, length: { in: 1..30 }, allow_blank: true

  protected

  def social_profile(provider)
    social_profiles.select{ |sp| sp.provider == provider.to_s }.first
  end
end

app/controllers/user/base.rb
class User::Base < ApplicationController
  layout 'user'
end

app/controllers/user/top_controller.rb
class User::TopController < User::Base
  include SmartYoyakuApi::User
  before_action :set_categories
  before_action :not_found, only: :details

  def index
  end

  def shop
    if params[:category_id].present?
      @category = Category.find(params[:category_id])
      @all_store = Store.categorized(params[:category_id]).active
    else
      @all_store = Store.active
    end
  end

  def details
    @reserve_app_url = reserve_app_url
    @plans = @store.plans
    @masseurs = @store.masseurs
    # 閲覧中のstoreが持っている出張範囲(各マッサージ師が持っている出張範囲)を全て取得
    ranges = @masseurs.map { |masseur| masseur.business_trip_ranges.pluck(:city_id).map {|id| City.find_by(id: id) }}
    # 取得した出張範囲で被っている出張範囲を一つにする。 それぞれのIDを取得
    @prefecture_ids = ranges.flatten.uniq.map {|city| city.prefecture_id}
    @city_ids = ranges.flatten.uniq.map {|city| city.id}

    @store_images = @store.store_images.first
    unless @store_images.nil?
      @count_store_image = @store_images.store_image.count
    end
  end

  private

    # ヘッダーとトップページのカテゴリ一覧表示用
    def set_categories
      @categories = Category.all
    end

    # @storeのstore_managerが無料プラン契約中の場合404エラーを表示
    def not_found
      @store = Store.find(params[:id])
      if @store.store_manager.order_plan.nil?
        raise ActiveRecord::RecordNotFound, "こちらのページは現在表示することができません。"
      end
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  require 'net/http'
  require 'uri'
  require 'json'

  def line; basic_action end

  private

  def basic_action
    @omniauth = request.env['omniauth.auth']
    if @omniauth.present?
      @profile = SocialProfile.where(provider: @omniauth['provider'], uid: @omniauth['uid']).first
      if @profile
        @profile.set_values(@omniauth)
        sign_in(:user, @profile.user)
      else
        @profile = SocialProfile.new(provider: @omniauth['provider'], uid: @omniauth['uid'])
        email = @omniauth['info']['email'] ? @omniauth['info']['email'] : "#{@omniauth['uid']}-#{@omniauth['provider']}@example.com"
        @profile.user = current_user || User.create!(email: email, name: @omniauth['info']['name'], password: Devise.friendly_token[0, 20])
        @profile.set_values(@omniauth)
        sign_in(:user, @profile.user)
        # redirect_to edit_user_path(@profile.user.id) and return
      end
    end
    flash[:success] = "ログインしました。"
    redirect_to root_path
  end
  
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # layout 'user' <- 有効にするとheaderとfotterが3回表示されレイアウトが崩れる

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # before_action :authenticate_user!, only: [:show] <- 動作しなかったのでs代わりにigned_in_userを作成
  before_action :signed_in_user, only: [:show]
  before_action :correct_user, only: [:show]

  def show
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected 

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  # userのログイン後の画面を指定
  # users/registrations_controllerに移すと動作しなくなる

  # user情報の更新後の画面を指定
  def after_update_path_for(users)
    user_path(current_user)
  end

  # ログイン中ユーザーの有無を確認
  def signed_in_user
    unless user_signed_in?
      flash[:alert] = "ログインしてください。"
      redirect_to new_user_session_url
    end
  end

  # アクセスしたユーザーが現在ログインしているユーザーか確認します。
  def correct_user
    unless (params[:id]) == current_user.id.to_s
      flash[:notice] = "アクセス権限がありません。"
      redirect_to root_url
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/top_helper.rb
module TopHelper

  def category
    @category.present? ? "【#{@category.category_name}】" : "全てのマッサージ店"
  end
end

app/views/user/top/index.html.erb
<!-- Breadcrumb Section Begin -->
<div class="breacrumb-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="breadcrumb-text"> <a href="#"><i class="fa fa-home"></i> Smart Portal</a> <span>Category</span> </div>
        <% flash.each do |message_type, msg| %>
          <div class="alert alert-success">
            <%= msg %>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</div>
<!-- Breadcrumb Section Begin -->
<!-- Product Shop Section Begin -->
<section class="product-shop spad">
  <div class="container">
    <div class="row">
      <!-- カテゴリ一覧 -->
      <div class="col-lg-3 col-md-6 col-sm-8 order-2 order-lg-1 produts-sidebar-filter">
        <div class="filter-widget">
          <h4 class="fw-title">カテゴリ一覧</h4>
          <ul class="filter-catagories">
            <% @categories.each do |category| %>
              <li>
                <%= link_to "#{category.category_name}", shop_path(category_id: category.id) %>
              </li>
            <% end %>
            <li><%= link_to "全てのカテゴリ", shop_path %></li>
          </ul>
        </div>
      </div>
      <!-- カテゴリ一覧 end -->
      <!-- 特集 -->
      <div class="col-lg-9 order-1 order-lg-2">
        <div class="product-show-option">
          <h4 class="fw-title"> 出張マッサージ専用スマートポータルサイト </h4>
        </div>
        <div class="product-list">
          <div class="row">
            <div class="col-lg-12 col-sm-12">
              <div class="product-item">
                <div class="pi-pic"> <img src="images/categories/category-0.jpg" alt="">
                  <%# <div class="sale pp-sale">Pick Up</div> %>
                </div>
                <div class="pi-text">
                  <a href="/shop" class="stretched-link">
                    <h5>〜自宅や宿泊先まで来てくれるなんて楽ちん！出張／訪問マッサージ〜</h5>
                  </a>
                </div>
              </div>
            </div>
          </div>
          <!-- row end -->
        </div>
        <!-- product-list end -->
        <hr>
        <!-- 人気のカテゴリ -->
        <div class="row">
          <h4 style="width: 100%; height: 30px;" class="pl-4 mb-4 mt-5">ピックアップカテゴリ</h4>
          <!-- カテゴリ 1 -->
          <div class="col-lg-4 col-sm-6">
            <div class="product-item">
              <div class="pi-pic"> <img src="images/categories/category-1.jpg" alt=""> </div>
              <div class="pi-text">
                <a href="/shop?category_id=1" class="mb-5 stretched-link">
                  <h5>整体</h5>
                </a>
              </div>
            </div>
          </div>
          <!-- カテゴリ 2 -->
          <div class="col-lg-4 col-sm-6">
            <div class="product-item">
              <div class="pi-pic"> <img src="images/categories/category-2.jpg" alt=""> </div>
              <div class="pi-text">
                <a href="/shop?category_id=2" class="mb-5 stretched-link">
                  <h5>骨格矯正</h5>
                </a>
              </div>
            </div>
          </div>
          <!-- カテゴリ 3 -->
          <div class="col-lg-4 col-sm-6">
            <div class="product-item">
              <div class="pi-pic"> <img src="images/categories/category-3.jpg" alt=""> </div>
              <div class="pi-text">
                <a href="/shop?category_id=3" class="mb-5 stretched-link">
                  <h5>スポーツマッサージ</h5>
                </a>
              </div>
            </div>
          </div>
          <!-- カテゴリ 4 -->
          <div class="col-lg-4 col-sm-6">
            <div class="product-item">
              <div class="pi-pic"> <img src="images/categories/category-4.jpg" alt=""> </div>
              <div class="pi-text">
                <a href="/shop?category_id=4" class="mb-5 stretched-link">
                  <h5>アロマセラピー</h5>
                </a>
              </div>
            </div>
          </div>
          <!-- カテゴリ 5 -->
          <div class="col-lg-4 col-sm-6">
            <div class="product-item">
              <div class="pi-pic"> <img src="images/categories/category-5.jpg" alt=""> </div>
              <div class="pi-text">
                <a href="/shop?category_id=6" class="mb-5 stretched-link">
                  <h5>按摩</h5>
                </a>
              </div>
            </div>
          </div>
          <!-- カテゴリ 6 -->
          <div class="col-lg-4 col-sm-6">
            <div class="product-item">
              <div class="pi-pic"> <img src="images/categories/category-6.jpg" alt=""> </div>
              <div class="pi-text">
                <a href="/shop?category_id=9" class="mb-5 stretched-link">
                  <h5>リフレクソロジー</h5>
                </a>
              </div>
            </div>
          </div>
        </div>
        <!-- row end -->
        <%# <hr>
        <!-- 最近利用した施術 -->
        <div class="row">
          <h4 style="width: 100%; height: 30px;" class="pl-4 mb-4 mt-5">最近利用した施術</h4>
          <div class="col-lg-4 col-sm-6">
            <div class="product-item">
              <div class="pi-pic"> <img src="images/categories/category-0.jpg" alt=""> </div>
              <div class="pi-text">
                <a href="#" class="mb-2 stretched-link">
                  <h5>出張ケア 90分コース</h5>
                </a>
                <div class="product-price"> 10,000円(税込) </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-sm-6">
            <div class="product-item">
              <div class="pi-pic"> <img src="images/categories/category-4.jpg" alt=""> </div>
              <div class="pi-text">
                <a href="#" class="mb-2 stretched-link">
                  <h5>アロマセラピー120分全身</h5>
                </a>
                <div class="product-price"> 15,000円(税込) </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-sm-6">
            <div class="product-item">
              <div class="pi-pic"> <img src="images/categories/category-4.jpg" alt=""> </div>
              <div class="pi-text">
                <a href="#" class="mb-2 stretched-link">
                  <h5>アロマセラピー120分全身</h5>
                </a>
                <div class="product-price"> 15,000円(税込) </div>
              </div>
            </div>
          </div>
        </div>
        <!-- row end -->
        <hr class="my-5">
        <!-- 口コミ -->
        <div class="col-lg-12">
          <h4 style="width: 100%; height: 30px;" class="mb-3 mt-5">新着口コミ</h4>
          <p class="pb-1">Smart Portal サイトで実際にサービスを利用したユーザーの満足度をチェック！</p>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <div class="blog-details-inner">
              <div class="posted-by">
                <div class="pb-pic"> <img src="images/blog/post-by.png" alt=""> </div>
                <div class="pb-text">
                  <a href="#">
                    <h5>ヒロさん</h5>
                  </a>
                  <p>当日予約にもかかわらずすぐに返事を頂き、マッサージも力加減など全てに満足です。翌日は、痛み、重さも嘘のように なくなってました。又、利用したいと思います。</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <div class="blog-details-inner">
              <div class="posted-by">
                <div class="pb-pic"> <img src="images/blog/post-by.png" alt=""> </div>
                <div class="pb-text">
                  <a href="#">
                    <h5>くみさん</h5>
                  </a>
                  <p>出張マッサージは初めてで少し不安もあったのですが親切な対応で大満足でした。またお願いしたいと思います。ありがとうございました。</p>
                </div>
              </div>
            </div>
          </div>
          <!-- 口コミ end -->
        </div>
        <!-- col-lg-9 order-1 order-lg-2 end -->
      </div> %>
      <!-- row end -->
    </div>
    <!-- container end -->
</section>
    <!-- Product Shop Section End -->
    
    <!-- Js Plugins -->
    <!--
    <script src="assets/js/jquery-3.3.1.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/jquery-ui.min.js"></script>
    <script src="assets/js/jquery.countdown.min.js"></script>
    <script src="assets/js/jquery.nice-select.min.js"></script>
    <script src="assets/js/jquery.zoom.min.js"></script>
    <script src="assets/js/jquery.dd.min.js"></script>
    <script src="assets/js/jquery.slicknav.js"></script>
    <script src="assets/js/owl.carousel.min.js"></script>
    <script src="assets/js/main.js"></script> -->

app/views/user/top/shop.html.erb
<section class="product-shop spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6 col-sm-8 order-2 order-lg-1 produts-sidebar-filter">
        <div class="box29">
          <!--<div class="box-title"></div>
          <h5 class="star_rate"></h5>
          <p></p>
        </div>
        <div class="box2">
          <p>ここに文章</p>
        </div>
        <div class="filter-widget">
          <h4 class="fw-title">一覧</h4>
          <ul class="filter-catagories">
            <li><a href="#">a</a></li>
            <li><a href="#">b</a></li>
            <li><a href="#">c</a></li>
          </ul>
        </div>-->
      </div>
    </div>
    <div class="col-lg-9 order-1 order-lg-2">
      <div class="product-show-option">
        <div class="list_head">
          <h4 class="fw-title">店舗一覧</h4>
          <ul class="list-sort nav nav-tabs">
            <li class="on space_box">
              <a herf="####">
                <span class="sort-name"><%= category %></span>
              </a>
            </li>
            <li class="on space_box">
              <a herf="####">
                <span class="sort-name"></span>
              </a>
            </li>
            <li class="on space_box">
              <a herf="####">
                <span class="sort-name"></span>
              </a>
            </li>
            <li class="on space_box">
              <a herf="####">
                <span class="sort-name"></span>
              </a>
            </li>
          </ul>
        </div>
        <% @all_store.each do |store| %>
          <div class="">
            <div class="row">
              <div class="col-lg-12">
               <div class="s_top_space">
                &emsp;<%= link_to store.store_name, details_path(store), class:"bottom_space_10 white-space_n" %>
                <div class="posted-by">
                  <div class="pb-pic list-mgr-img-box">
                    <%  store_images = store.store_images.first %>
                    <% unless store_images.nil? %>
                      <% if store_images.store_image.present? %>
                        <img src="<%= store_images.store_image[0].url %>" alt="" class="all_store_store_image">
                      <% else %>
                        <img src="../images/no_image.jpg" alt="" class="all_store_store_image">
                      <% end %>
                    <% else %>
                      <img src="../images/no_image.jpg" alt="" class="all_store_store_image">
                    <% end %>
                  </div>
                  <div class="pb-text ">
                    <p class="posted_text "><%= store.store_description %></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </section>
    </div>
  </div>
</section>

<!-- Js Plugins -->
<!--
<script src="assets/js/jquery-3.3.1.min.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script src="assets/js/jquery-ui.min.js"></script>
<script src="assets/js/jquery.countdown.min.js"></script>
<script src="assets/js/jquery.nice-select.min.js"></script>
<script src="assets/js/jquery.zoom.min.js"></script>
<script src="assets/js/jquery.dd.min.js"></script>
<script src="assets/js/jquery.slicknav.js"></script> 
<script src="assets/js/owl.carousel.min.js"></script>
<script src="assets/js/main.js"></script> -->