config/routes.rb
Rails.application.routes.draw do

  # User↓========================================================================================
    root            to: "user/top#index"
    get "/shop",    to: "user/top#shop"
    get "/store/:id", to: "user/top#details", as: :details
  # devise↓ =====================================================================================
    devise_for :admins, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    devise_for :masseurs
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    devise_scope :user do
      get "/user/:id", :to => "users/registrations#show", as: :user
    end

    devise_for :users, controllers: {
      sessions:      'users/sessions',
      passwords:     'users/passwords',
      registrations: 'users/registrations',
      omniauth_callbacks: "users/omniauth_callbacks"
    }
    devise_for :store_managers, :controllers => {
      :registrations => 'store_managers/registrations',
      :sessions => 'store_managers/sessions'
    }
    devise_scope :store_manager do
      get "store_managers/:id", :to => "store_managers/registrations#show", as: "store_managers_show"
      get "store_managers/:id/reservations", :to => "store_managers/registrations#index", as: "store_managers_index"
      get "store_manager/:id/detales", :to => "store_managers/registrations#detales", as: "store_managers_detales"
      get "store_managers/sign_out", :to => "store_managers/sessions#destroy"
    end

    # devise_scope :store_managers do
    #   get "sign_in", :to => "store_managers/sessions#new"
    #   get "sign_out", :to => "store_managers/sessions#destroy"
    # end


    

  # Admin↓========================================================================================
    namespace :admin do
    #  get '/top', to: 'admins#top'
    end

  # Masseur↓========================================================================================
    namespace :masseur do

    end

  # Store_manager↓========================================================================================
    namespace :store_manager do
      get "/:id/top", to: 'top_page#top'
      patch "update_calendar_status", to: 'top_page#update_calendar_status'
      resources :store
      resources :plans
      resources :masseurs, except: :show
      # 出張範囲のrouting↓========================================================================================
      get "/masseurs/business_trip_ranges", :to => "/store_manager/business_trip_ranges#index"
      get "/masseurs/:masseur_id/business_trip_ranges/edit", :to => "/store_manager/business_trip_ranges#edit", as: "business_trip_ranges_edit"
      get "/masseurs/:masseur_id/business_trip_ranges/show", :to => "/store_manager/business_trip_ranges#show", as: "business_trip_ranges_show"
      patch "/masseurs/:masseur_id/business_trip_ranges/update", :to => "/store_manager/business_trip_ranges#update", as: "business_trip_ranges_update"
      get "/masseurs/:masseur_id/business_trip_ranges/cities_select", :to => "/store_manager/business_trip_ranges#cities_select", as: "cities_select_business_trip_ranges"
    end

    # SmartYoyaku webhook↓==========================================================================
    namespace :smart_yoyaku do
      post "webhook", to: 'webhook#update_order_plan'
    end
    
end

app/views/layouts/_fotter.html.erb
<!-- Footer Section Begin -->
    <footer class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="footer-left">
                        <div class="footer-logo">
                            <a href="#"><img src="/images/logo2.png" alt=""></a>
                        </div>
                        <!--<ul>
                            <li>Address: 60-49 Road 11378 New York</li>
                            <li>Phone: +65 11.188.888</li>
                            <li>Email: hello.colorlib@gmail.com</li>
                        </ul>-->
                        <!--<div class="footer-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>-->
                    </div>
                </div>
                <div class="col-lg-2 offset-lg-1">
                    <div class="footer-widget">
                        <!--<h5>Information</h5>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Checkout</a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">Serivius</a></li>
                        </ul>-->
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="footer-widget">
                        <h5>アカウント</h5>
                        <ul>
                            <% if user_signed_in? %>
                                <li><%= link_to "マイページ", user_path(current_user) %></li>
                                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                            <% else %>
                                <li><%= link_to "ログイン", new_user_session_path %></a></li>
                                <li><%= link_to "新規会員登録", new_user_registration_path %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="footer-widget">
                        <h5>Smart Portal システム</h5>
                        <ul>
                            <li><a href="#">管理システムログイン</a></li>
                            <li><a href="#">Smart Portalサイトに出店希望の方</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright-reserved">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="copyright-text">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </div>
                        <!--<div class="payment-pic">
                            <img src="/images/payment-method.png" alt="">
                        </div>-->
                    </div>
                </div>
            </div>
        </div>
    </footer>

app/views/layouts/_header.html.erb
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Fashi Template">
    <meta name="keywords" content="Fashi, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Fashi | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,500,600,700,800,900&display=swap" rel="stylesheet">
</head>
    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="container">
            <div class="inner-header">
                <div class="row">
                    <div class="col-lg-3 col-md-3">
                        <div class="logo">
                            <a href="./">
                                <img src="/images/logo1.png" alt="">
                            </a>
                        </div>
                    </div>
                    <!--<div class="col-lg-7 col-md-7">
                        <div class="advanced-search">
                            <button type="button" class="category-btn">All Categories</button>
                            <form action="#" class="input-group">
                                <input type="text" placeholder="What do you need?">
                                <button type="button"><i class="ti-search"></i></button>
                            </form>
                        </div>
                    </div>-->
                    <!-- mobile menu表示時用 -->
                    <div class="col-lg-2 col-md-2">
                        <p>&emsp;</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="nav-item">
            <div class="container">
                <div class="nav-depart">
                    <div class="depart-btn">
                        <i class="ti-menu"></i>
                        <span>カテゴリ一覧</span>
                        <ul class="depart-hover">
                            <% @categories.each do |category| %>
                                <li><%= link_to "#{category.category_name}", shop_path(category_id: category.id) %></li>
                            <% end %>
                            <li><%= link_to "全てのカテゴリ", shop_path %></li>
                        </ul>
                    </div>
                </div>
                <nav class="nav-menu mobile-menu">
                    <ul>
                        <li><%= link_to "トップ", root_path %></li>
                        <li><%= link_to "一覧ページ", shop_path %></li>
                        <!--<li><%= link_to "詳細", "#" %></li>
                        <li><a href="./blog.html">Blog</a></li>
                        <li><a href="./contact.html">Contact</a></li>-->
                        <!-- 以下は(仮)Decorator導入の際に整える -->
                        <% if user_signed_in? %>
                            <li><%= link_to "#{current_user.name}", "#" %>
                                <ul class="dropdown">
                                    <li><%= link_to "マイページ", user_path(current_user) %></li>
                                    <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                                </ul>
                            </li>
                        <% elsif store_manager_signed_in? %>
                            <li><%= link_to "#{current_store_manager.name}", "#" %>
                                <ul class="dropdown">
                                    <li><%= link_to "マイページ", store_manager_path(current_store_manager) %>
                                    <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                                </ul>
                            </li>
                        <% else  %>
                            <li><a href="#">アカウント</a>
                                <ul class="dropdown">
                                    <li><%= link_to "ログイン", new_user_session_path %></li>
                                    <li><%= link_to "新規会員登録", new_user_registration_path %></li>
                                    <li><%= link_to "マッサージ師として新規会員登録", new_store_manager_registration_path %>
                                    <li><%= link_to "マッサージ師としてログイン", new_store_manager_session_path %></li>
                                </ul>
                            </li>
                        <% end %>
                    </ul>
                </nav>
                <div id="mobile-menu-wrap"></div>
            </div>
        </div>
    </header>
    <!-- Header End -->
    <!-- 以下を消すとスマホ用のメニューが表示されなくなる -->
    <script src="/assets/js/jquery-3.3.1.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/jquery-ui.min.js"></script>
    <script src="/assets/js/jquery.countdown.min.js"></script>
    <script src="/assets/js/jquery.nice-select.min.js"></script>
    <script src="/assets/js/jquery.zoom.min.js"></script>
    <script src="/assets/js/jquery.dd.min.js"></script>
    <script src="/assets/js/jquery.slicknav.js"></script>
    <script src="/assets/js/owl.carousel.min.js"></script>
    <script src="/assets/js/main.js"></script>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smartポータル</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
<% content_for :content do %>
  <%= yield %>
<% end %>
<%= render template: "layouts/application" %>
</body>
</html>

app/views/layouts/application.html.erb
<%= content_for?(:content) ? yield(:content) : yield %>

app/views/layouts/masseur.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smartポータル</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'masseur', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'masseur', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
<% content_for :content do %>
  <%= yield %>
<% end %>
<%= render template: "layouts/application" %>
</body>
</html>

app/views/layouts/store.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smartポータル</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'store', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'store', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
<% content_for :content do %>
  <%= yield %>
<% end %>
<%= render template: "layouts/application" %>
</body>
</html>

app/views/layouts/store_manager.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Smartポータル</title>
    <%= csrf_meta_tags %>
    <meta http-equiv="content-language" content="ja"> <!-- ページに中国語翻訳表示が出ないように対応 -->
    <%= stylesheet_link_tag    'store_manager', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'store_manager', 'data-turbolinks-track': 'reload' %>
    <script src="//code.jquery.com/jquery-1.12.1.min.js"></script>
  </head>
<body>
<% content_for :content do %>
  <%= yield %>
<% end %>
<%= render template: "layouts/application" %>
</body>
</html>

app/views/layouts/store_managers.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smartポータル</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'store_managers', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'store_managers', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
<% content_for :content do %>
  <%= yield %>
<% end %>
<%= render template: "layouts/application" %>
</body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smartポータル</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'user', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'user', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
  <% content_for :content do %>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/fotter' %>
  <% end %>
  <%= render template: "layouts/application" %>
</body>
</html>

app/views/layouts/users.html.erb
<!-- deviseによって作成されたviewファイル用、headerとfotterを含まない -->
<!DOCTYPE html>
<html>
  <head>
    <title>Smartポータル</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'user', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'user', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
  <% content_for :content do %>
    <%= yield %>
  <% end %>
  <%= render template: "layouts/application" %>
</body>
</html>